"""add subcategory to products

Revision ID: b417cee2f88f
Revises: e98c01defacf
Create Date: 2026-04-09 17:05:53.109093

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b417cee2f88f"
down_revision: Union[str, Sequence[str], None] = "e98c01defacf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("subcategory", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "subcategory")
    # ### end Alembic commands ###
