"""initial

Revision ID: e362ea13cdbe
Revises: 
Create Date: 2026-04-08 11:36:55.032036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e362ea13cdbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bikes', 'article',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bikes', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bikes', 'youtube_url',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=True)
    op.alter_column('brands', 'logo',
               existing_type=sa.VARCHAR(length=300),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reviews', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('reviews', 'reply')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reply', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('reviews', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('brands', 'logo',
               existing_type=sa.VARCHAR(length=300),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('bikes', 'youtube_url',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('bikes', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'available'::character varying"),
               existing_nullable=True)
    op.alter_column('bikes', 'article',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
