"""add color field to products

Revision ID: e98c01defacf
Revises: 01df2261f58c
Create Date: 2026-04-09 16:47:45.341485

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e98c01defacf"
down_revision: Union[str, Sequence[str], None] = "01df2261f58c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("color", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "color")
    # ### end Alembic commands ###
